"""
This script creates a structured taxonomy based on UNESCO Fields of Science classification
and saves it to a JSON file in the system_data directory.
"""

import json
import os

# Base taxonomy structure that can be used in a Python script
BASE_TAXONOMY = {
    "natural_sciences": {
        "biology": {
            "aerobiology": {},
            "anatomy": {
                "comparative_anatomy": {},
                "human_anatomy": {}
            },
            "bacteriology": {},
            "biochemistry": {},
            "bioinformatics": {},
            "biophysics": {},
            "biotechnology": {},
            "botany": {
                "ethnobotany": {},
                "phycology": {}
            },
            "cell_biology": {},
            "chronobiology": {},
            "cognitive_biology": {},
            "computational_biology": {},
            "conservation_biology": {},
            "cryobiology": {},
            "developmental_biology": {
                "embryology": {},
                "gerontology": {},
                "teratology": {}
            },
            "ecology": {
                "agroecology": {},
                "ethnoecology": {},
                "human_ecology": {},
                "landscape_ecology": {}
            },
            "forensic_biology": {},
            "genetics": {
                "behavioural_genetics": {},
                "molecular_genetics": {},
                "population_genetics": {}
            },
            "geobiology": {},
            "endocrinology": {},
            "evolution": {
                "systematics": {},
                "taxonomy": {}
            },
            "histology": {},
            "human_biology": {},
            "immunology": {},
            "limnology": {},
            "linnaean_taxonomy": {},
            "marine_biology": {},
            "mathematical_biology": {},
            "microbiology": {},
            "molecular_biology": {},
            "mycology": {},
            "neuroscience": {
                "behavioral_neuroscience": {},
                "neurophysics": {},
                "computational_neuroscience": {}
            },
            "nutrition": {},
            "paleobiology": {
                "paleontology": {}
            },
            "parasitology": {},
            "pathology": {
                "anatomical_pathology": {},
                "clinical_pathology": {},
                "dermatopathology": {},
                "forensic_pathology": {},
                "hematopathology": {},
                "histopathology": {},
                "molecular_pathology": {},
                "surgical_pathology": {},
                "phytopathology": {}
            },
            "physiology": {
                "human_physiology": {
                    "exercise_physiology": {}
                }
            },
            "population_biology": {},
            "quantum_biology": {},
            "sociobiology": {},
            "structural_biology": {},
            "systems_biology": {},
            "theoretical_biology": {},
            "toxicology": {},
            "virology": {
                "molecular_virology": {}
            },
            "xenobiology": {},
            "zoology": {
                "animal_communications": {},
                "apiology": {},
                "arachnology": {},
                "arthropodology": {},
                "batrachology": {},
                "bryozoology": {},
                "carcinology": {},
                "cetology": {},
                "cnidariology": {},
                "entomology": {
                    "forensic_entomology": {}
                },
                "ethnozoology": {},
                "ethology": {},
                "helminthology": {},
                "herpetology": {},
                "ichthyology": {},
                "invertebrate_zoology": {},
                "mammalogy": {
                    "cynology": {},
                    "felinology": {}
                },
                "malacology": {
                    "conchology": {},
                    "limacology": {},
                    "teuthology": {}
                },
                "myriapodology": {},
                "myrmecology": {},
                "nematology": {},
                "neuroethology": {},
                "oology": {},
                "ornithology": {},
                "planktology": {},
                "primatology": {},
                "zootomy": {},
                "zoosemiotics": {}
            }
        },
        "chemistry": {
            "agrochemistry": {},
            "analytical_chemistry": {},
            "astrochemistry": {},
            "atmospheric_chemistry": {},
            "biochemistry": {},
            "catalysts": {},
            "chemical_engineering": {},
            "chemical biology": {},
            "chemical_physics": {},
            "cheminformatics": {},
            "computational_chemistry": {},
            "cosmochemistry": {},
            "environmental_chemistry": {},
            "femtochemistry": {},
            "flow_chemistry": {},
            "forensic_chemistry": {},
            "geochemistry": {},
            "green_chemistry": {},
            "histochemistry": {},
            "immunochemistry": {},
            "inorganic_chemistry": {},
            "marine_chemistry": {},
            "mathematical_chemistry": {},
            "mechanochemistry": {},
            "medicinal_chemistry": {},
            "molecular_biology": {},
            "molecular_mechanics": {},
            "nanotechnology": {},
            "natural_product_chemistry": {},
            "neurochemistry": {},
            "oenology": {},
            "organic_chemistry": {},
            "organometallic_chemistry": {},
            "petrochemistry": {},
            "pharmacology": {},
            "photochemistry": {},
            "physical_chemistry": {
                "electrochemistry": {},
                "physical_organic_chemistry": {}
            },
            "phytochemistry": {},
            "polymer_chemistry": {},
            "quantum_chemistry": {},
            "radiochemistry": {},
            "soil_chemistry": {},
            "solid_state_chemistry": {},
            "sonochemistry": {},
            "supramolecular_chemistry": {},
            "surface_chemistry": {},
            "synthetic_chemistry": {},
            "systems_chemistry": {},
            "theoretical_chemistry": {},
            "thermochemistry": {}
        },
        "earth_sciences": {
            "atmospheric_science": {},
            "climatology": {},
            "ecology": {},
            "edaphology": {},
            "environmental_science": {},
            "environmental_chemistry": {},
            "forensic_geology": {},
            "gemology": {},
            "geobiology": {},
            "geodesy": {},
            "geography": {},
            "geology": {},
            "geochemistry": {},
            "geomorphology": {},
            "geophysics": {},
            "glaciology": {},
            "hydrogeology": {},
            "hydrology": {},
            "meteorology": {},
            "mineralogy": {},
            "limnology": {},
            "oceanography": {},
            "pedology": {},
            "paleontology": {
                "paleobiology": {},
                "paleoecology": {}
            },
            "petrology": {},
            "planetary_science": {},
            "sedimentology": {},
            "seismology": {},
            "soil_science": {},
            "speleology": {},
            "tectonics": {},
            "volcanology": {}
        },
        "physics": {
            "acoustics": {
                "quantum_acoustics": {}
            },
            "agrophysics": {},
            "applied_physics": {
                "accelerator_physics": {},
                "communication_physics": {}
            },
            "astrophysics": {},
            "atmospheric_physics": {
                "atmospheric_electricity": {}
            },
            "atomic_physics": {},
            "molecular_physics": {},
            "optical_physics": {},
            "biophysics": {
                "neurophysics": {}
            },
            "chemical_physics": {},
            "classical_physics": {},
            "computational_physics": {},
            "condensed_matter_physics": {},
            "cryogenics": {},
            "digital_physics": {},
            "dynamics": {
                "analytical_dynamics": {},
                "astrodynamics": {},
                "brownian_dynamics": {},
                "file_dynamics": {},
                "flight_dynamics": {},
                "fluid_dynamics": {},
                "aerodynamics": {},
                "hydrodynamics": {},
                "fractional_dynamics": {},
                "geodynamics": {},
                "molecular_dynamics": {},
                "newtonian_dynamics": {},
                "langevin_dynamics": {},
                "quantum_chromodynamics": {},
                "quantum_electrodynamics": {},
                "relativistic_dynamics": {},
                "stellar_dynamics": {},
                "system_dynamics": {},
                "thermodynamics": {},
                "vehicle_dynamics": {}
            },
            "econophysics": {},
            "electromagnetism": {
                "electricity": {},
                "magnetism": {}
            },
            "engineering_physics": {},
            "experimental_physics": {},
            "geophysics": {
                "biogeophysics": {},
                "geomagnetism": {}
            },
            "kinematics": {
                "fluid_kinematics": {},
                "relativistic_kinematics": {}
            },
            "kinetics": {
                "electrokinetics": {},
                "homeokinetics": {}
            },
            "laser_physics": {},
            "materials_physics": {},
            "mathematical_physics": {},
            "medical_physics": {},
            "mechanics": {
                "analytical_mechanics": {},
                "applied_mechanics": {},
                "ballistics": {},
                "biomechanics": {},
                "celestial_mechanics": {},
                "classical_mechanics": {},
                "continuum_mechanics": {},
                "fluid_mechanics": {},
                "fracture_mechanics": {},
                "hamiltonian_mechanics": {},
                "hydraulics": {},
                "lagrangrian_mechanics": {},
                "matrix_mechanics": {},
                "molecular_mechanisms": {},
                "optomechanics": {},
                "particle_mechanics": {},
                "quantum_mechanics": {},
                "relativistic_mechanics": {},
                "relativistic_quantum_mechanics": {},
                "soil_mechanics": {},
                "solid_mechanics": {},
                "statistical_mechanics": {}
            },
            "mineral_physics": {},
            "molecular_physics": {},
            "nuclear_physics": {},
            "optics": {
                "geometrical_optics": {},
                "physical_optics": {},
                "quantum_optics": {}
            },
            "particle_physics": {},
            "petrophysics": {},
            "photonics": {},
            "physical_chemistry": {},
            "plasma_physics": {},
            "polymer_physics": {},
            "quantum_physics": {
                "quantum_technology": {}
            },
            "radiophysics": {},
            "relativity": {
                "general_relativity": {},
                "special_relativity": {}
            },
            "social_physics": {},
            "soil_physics": {},
            "solid_state_physics": {},
            "spintronics": {},
            "fluid_statics": {},
            "statistical_physics": {},
            "surface_physics": {},
            "theoretical_physics": {},
            "quantum_field_theory": {},
            "quantum_gravity": {},
            "thermal_physics": {}
        },
        "space_sciences": {
            "aerospace_engineering": {
                "aerospace_architecture": {},
                "aerospace_physiology": {},
                "aerospace_manufacturing": {},
                "astronautics": {
                    "space_architecture": {},
                    "space_colonization": {},
                    "space_commercialization": {
                        "space_based_economy": {},
                        "space_industry": {},
                        "space_manufacturing": {},
                        "space_tourism": {}
                    },
                    "space_environment": {},
                    "space_logistics": {},
                    "space_food": {},
                    "space_medicine": {},
                    "space_religion": {},
                    "space_sex": {},
                    "space_survival": {},
                    "space_warfare": {},
                    "space_writing": {}
                },
                "aeronautics": {},
                "control_engineering": {},
                "human_spaceflight": {},
                "robotic_spacecraft": {},
                "space_corrosion": {}
            },
            "space_technology": {
                "space_telescopes": {},
                "space_based_radar": {},
                "space_based_solar_power": {},
                "spacecraft_design": {},
                "spacecraft_propulsion": {}
            },
            "asteroid_impact_avoidance": {},
            "astrobiology": {},
            "astrobotany": {},
            "astrochemistry": {},
            "cosmochemistry": {},
            "cosmology": {
                "physical_cosmology": {}
            },
            "micro_gravity_environment_research": {},
            "remote_sensing": {},
            "space_archaeology": {},
            "space_exploration": {},
            "space_law": {},
            "space_nuclear_power": {},
            "astronomy": {
                "archaeoastronomy": {},
                "astrometry": {},
                "amateur_astronomy": {},
                "forensic_astronomy": {},
                "extra_galactic_astronomy": {},
                "galactic_astronomy": {},
                "high_energy_astronomy": {},
                "observational_astronomy": {
                    "radio_astronomy": {},
                    "microwave_astronomy": {},
                    "submillimetre_astronomy": {},
                    "infrared_astronomy": {},
                    "optical_astronomy": {},
                    "uv_astronomy": {},
                    "x_ray_astronomy": {},
                    "gamma_ray_astronomy": {},
                    "cosmic_ray_astronomy": {},
                    "neutrino_astronomy": {},
                    "gravitational_wave_astronomy": {}
                },
                "photometry": {},
                "spectroscopy": {},
                "stellar_astronomy": {},
                "solar_astronomy": {},
            },
            "astrophysics": {
                "celestial_mechanics": {},
                "compact_objects": {},
                "computational_astrophysics": {},
                "gravitational_astronomy": {
                    "black_holes": {}
                },
                "interstellar_medium": {},
                "numerical_simulations": {
                    "astrophysical_plasma": {},
                    "galaxy_formation_and_evolution": {},
                    "high_energy_astrophysics": {},
                    "hydrodynamics": {},
                    "magnetohydrodynamics": {},
                    "star_formation": {}
                },
                "orbital_mechanics": {},
                "physical_cosmology": {},
                "relativistic_astrophysics": {},
                "stellar_astrophysics": {
                    "helioseismology": {},
                    "solar_physics": {},
                    "stellar_evolution": {},
                    "stellar_nucleosynthesis": {}
                },
                "space_plasma_physics": {}
            },
            "planetary_science": {
                "atmospheric_science": {},
                "exoplanetology": {},
                "planetary_formation": {},
                "planetary_rings": {},
                "magnetospheres": {},
                "planetary_geology": {},
                "planetary_surfaces": {},
                "small_solar_system_bodies": {}
            }
        }
    },
    "formal_sciences": {
        "computer_science": {
            "theory_of_computation": {
                "automata_theory": {},
                "computability_theory": {},
                "computational_complexity_theory": {},
                "concurrency_theory": {}
            },
            "vlsi_design": {},
            "operating_systems": {},
            "algorithms": {
                "randomized_algorithms": {},
                "distributed_algorithms": {},
                "parallel_algorithms": {},
                "computational_geometry": {},
            },
            "databases": {
                "relational_database": {},
                "distributed_database": {},
                "object_database": {},
                "network_database": {}
            },
            "data_science": {},
            "data_structures": {},
            "computer_architecture": {},
            "computer_communications_networks": {
                "information_theory": {},
                "internet": {},
                "world_wide_web": {},
                "wireless_computing": {},
                "ubiquitous_computing": {},
                "cloud_computing": {}
            },
            "computer_programming": {},
            "computer_security": {
                "cryptanalysis": {},
                "cryptography": {},
                "fault_tolerant_computing": {}
            },
            "distributed_computing": {
                "grid_computing": {}
            },
            "parallel_computing": {
                "high_performance_computing": {}
            },
            "quantum_computing": {},
            "computer_graphics": {
                "image_processing": {},
                "scientific_visualization": {}
            },
            "software_engineering": {},
            "programming_languages": {
                "programming_paradigms": {
                    "imperative_programming": {},
                    "object_oriented_programming": {},
                    "functional_programming": {},
                    "logic_programming": {},
                    "concurrent_programming": {}
                },
                "program_semantics": {},
                "type_theory": {},
                "compilers": {}
            },
            "human_computer_interaction": {},
            "information_science": {
                "data_management": {},
                "data_mining": {},
                "information_retrieval": {},
                "information_management": {},
                "information_system": {},
                "information_technology": {},
                "knowledge_management": {},
                "multimedia": {},
                "hypermedia": {},
                "quantum_information": {}
            },
            "theoretical_computer_science": {},
            "artificial_intelligence": {},
            "cognitive_science": {},
            "machine_learning": {},
            "artificial_neural_networks": {},
            "support_vector_machines": {},
            "natural_language_processing": {},
            "computer_vision": {},
            "expert_systems": {},
            "robotics": {},
            "numerical_analysis": {},
            "algebraic_computation": {},
            "computational_number_theory": {},
            "computational_mathematics": {},
            "scientific_computing": {},
            "computational_biology": {},
            "computational_physics": {},
            "computational_chemistry": {},
            "computational_neuroscience": {},
            "computer_aided_engineering": {
                "finite_element_analysis": {},
                "computational_fluid_dynamics": {}
            },
            "computational_economics": {},
            "computational_sociology": {},
            "computational_finance": {},
            "digital_humanities": {},
            "history_of_computer_hardware": {},
            "history_of_computer_science": {},
            "humanistic_informatics": {},
            "community_informatics": {}
        },
        "logic": {
            "philosophical_logic": {
                "logical_reasoning": {},
                "modal_logic": {},
                "deontic_logic": {},
                "doxastic_logic": {}
            },
            "mathematical_logic": {
                "set_theory": {},
                "proof_theory": {},
                "model_theory": {},
                "recursion_theory": {},
                "modal_logic": {},
                "intuitionistic_logic": {}
            }
        },
        "mathematics": {
            "algebra": {
                "group_theory": {},
                "ring_theory": {},
                "commutative_algebra": {},
                "field_theory": {},
                "linear_algebra": {},
                "multilinear_algebra": {},
                "universal_algebra": {},
                "homological_algebra": {},
                "differential_algebra": {},
                "lattice_theory": {},
                "order_theory": {},
                "representational_theory": {},
                "k_theory": {},
                "category_theory": {},
                "topos_theory": {}
            },
            "analysis": {
                "real_analysis": {},
                "calculus": {},
                "complex_analysis": {},
                "functional_analysis": {},
                "operator_theory": {},
                "non_standard_analysis": {},
                "harmonic_analysis": {},
                "fourier_analysis": {},
                "p_adic_analysis": {},
                "ordinary_differential_equations": {},
                "partial_differential_equations": {},
            },
            "probability_theory": {
                "measure_theory": {},
                "integral_geometry": {},
                "ergodic_theory": {},
                "stochastic_process": {}
            },
            "geometry": {
                "algebraic_geometry": {},
                "projective_geometry": {},
                "affine_geometry": {},
                "non_euclidean_geometry": {},
                "convex_geometry": {},
                "discrete_geometry": {},
                "integral_geometry": {},
                "euclidean_geometry": {},
                "finite_geometry": {},
                "galois_geomtry": {},
                "noncommutative_geometry": {},
                "solid_geometry": {},
                "trigonometry": {}
            },
            "topology": {
                "general_topology": {},
                "algebraic_topology": {},
                "geometric_topology": {},
                "differential_topology": {},
            },
            "number_theory": {
                "analytic_number_theory": {},
                "algebraic_number_theory": {},
                "geometric_number_theory": {},
                "arithmetic": {},
                "arithmetic_combinatorics": {}
            },
            "approximation_theory": {},
            "computational_mathematics": {},
            "numerical_analysis": {},
            "operations_research": {
                "mathematical_optimization": {},
                "linear_programming": {},
                "dynamic_programming": {},
                "assignment_problem": {},
                "decision_analysis": {},
                "inventory_theory": {},
                "scheduling": {},
                "real_options_analysis": {},
                "systems_analysis": {},
                "stochastic_processes": {},
                "optimal_maintenance": {}
            },
            "chaos_theory": {},
            "fractal_geometry": {},
            "mathematical_physics": {
                "quantum_mechanics": {},
                "quantum_field_theory": {},
                "quantum_gravity": {},
                "string_theory": {},
                "statistical_mechanics": {}
            },
            "computational_complexity_theory": {},
            "information_theory": {},
            "cryptography": {},
            "steganography": {},
            "cominatorics": {
                "coding_theory": {}
            },
            "graph_theory": {},
            "game_theory": {},
            "statistics": {
                "econometrics": {},
                "actuaurial_science": {},
                "demography": {},
                "computational_statistics": {
                    "data_mining": {},
                    "regression": {},
                    "simulation": {}
                },
                "design_of_experiments": {
                    "block_design": {},
                    "analysis_of_variance": {},
                    "response_surface_methodology": {}
                },
                "sample_survey": {},
                "sampling_theory": {},
                "statistical_modeling": {
                    "biostatistics": {},
                    "epidemiology": {},
                    "multivariate_analysis": {},
                    "structural_equation_model": {},
                    "time_series": {},
                    "reliability_theory": {},
                    "quality_control": {}
                },
                "statistical_theory": {},
                "decision_theory": {},
                "probability": {},
                "survey_methodology": {}
            }
        },
        "systems_science": {
            "network_science": {},
            "chaos_theory": {},
            "conceptual_systems": {},
            "complex_systems": {},
            "cybernetics": {
                "biocybernetics": {},
                "engineering_cybernetics": {},
                "management_cybernetics": {},
                "medical_cybernetics": {},
                "new_cybernetics": {},
                "second_order_cybernetics": {},
                "sociocybernetics": {}
            },
            "control_theory": {
                "affect_control_theory": {},
                "control_engineering": {},
                "control_systems": {},
                "dynamical_systems": {},
                "perceptual_control_theory": {}
            },
            "operations_research": {},
            "systems_biology": {
                "computational_systems_biology": {},
                "synthetic_biology": {},
                "systems_immunology": {},
                "systems_neuroscience": {}
            },
            "systems_chemistry": {},
            "system_dynamics": {
                "social_dynamics": {}
            },
            "systems_ecology": {
                "ecosystem_ecology": {}
            },
            "systems_engineering": {
                "biological_systems_engineering": {},
                "earth_systems_engineering_and_management": {},
                "enterprise_systems_engineering": {},
                "systems_analysis": {}
            },
            "systems_theory_in_anthropology": {},
            "systems_psychology": {
                "ergonomics": {},
                "family_systems_theory": {},
                "systemic_therapy": {},
            },
            "systems_theory": {
                "biochemical_systems_theory": {},
                "ecological_systems_theory": {},
                "developmental_systems_theory": {},
                "general_systems_theory": {},
                "living_systems_theory": {},
                "lti_system_theory": {},
                "sociotechnical_systems_theory": {},
                "mathematical_systems_theory": {},
                "world_systems_theory": {}
            }
        }
    },
    "social_sciences": {
        "psychology": {
            "abnormal_psychology": {},
            "applied_psychology": {},
            "asian_psychology": {},
            "biological_psychology": {},
            "black_psychology": {},
            "clinical_psychology": {},
            "cognitive_psychology": {},
            "community_psychology": {},
            "comparative_psychology": {},
            "conservation_psychology": {},
            "consumer_psychology": {},
            "counseling_psychology": {},
            "criminal_psychology": {},
            "cultural_psychology": {},
            "developmental_psychology": {},
            "differential_psychology": {},
            "ecological_psychology": {},
            "educational_psychology": {},
            "environmental_psychology": {},
            "evolutionary_psychology": {},
            "experimental_psychology": {},
            "group_psychology": {},
            "family_psychology": {},
            "feminine_psychology": {},
            "forensic_psychology": {},
            "forensic_development_psychology": {},
            "health_psychology": {},
            "humanistic_psychology": {},
            "indigenous_psychology": {},
            "legal_psychology": {},
            "mathematical_psychology": {},
            "media_psychology": {},
            "medical_psychology": {},
            "military_psychology": {},
            "moral_psychology": {},
            "descriptive_ethics": {},
            "music_psychology": {},
            "neuropsychology": {},
            "occupational_psychology": {},
            "occupational_health_psychology": {},
            "organizational_psychology": {},
            "parapsychology": {},
            "pediatric_psychology": {},
            "pedology": {},
            "personality_psychology": {},
            "phenomenology": {},
            "political_psychology": {},
            "positive_psychology": {},
            "problem_solving": {},
            "psychoanalytics": {},
            "psychometrics": {},
            "psychology_of_religion": {},
            "psychopathology": {
                "child_psychopathology": {}
            },
            "psychophysics": {},
            "quantitative_psychology": {},
            "rehabilitation_psychology": {},
            "school_psychology": {},
            "social_psychology": {},
            "sport_psychology": {},
            "traffic_psychology": {},
            "transpersonal_psychology": {},
            "travel_psychology": {}
        },
        "sociology": {
            "analytical_sociology": {},
            "applied_sociology": {
                "political_sociology": {},
                "public_sociology": {},
                "social_engineering": {},
                "leisure_studies": {},
            },
            "architectural_sociology": {},
            "behavioral_sociology": {},
            "chinese_sociology": {},
            "collective_behavior": {
                "activism": {},
                "social_movements": {}
            },
            "social_phenomenon": {},
            "community_informatics": {
                "social_network_analysis": {},
            },
            "comparative_sociology": {},
            "conflict_theory": {},
            "critical_sociology": {},
            "cultural_sociology": {},
            "cultural_studies": {},
            "criminology": {},
            "critical_management_studies": {},
            "demography": {},
            "digital_sociology": {},
            "dramaturgical_sociology": {},
            "economic_sociology": {},
            "educational_sociology": {},
            "empirical_sociology": {},
            "environmental_sociology": {},
            "evolutionary_sociology": {},
            "feminist_sociology": {},
            "figurational_sociology": {},
            "futures_studies": {},
            "historical_sociology": {},
            "human_ecology": {},
            "humanistic_sociology": {},
            "industrial_sociology": {},
            "interactionism": {},
            "internet_sociology": {},
            "interpretive_sociology": {
                "phenomenology": {},
                "ethnomethodology": {},
                "symbolic_interactionism": {},
                "social_constructionism": {}
            },
            "jealousy_sociology": {},
            "macrosociology": {},
            "marxist_sociology": {},
            "mathematical_sociology": {},
            "medical_sociology": {},
            "mesosociology": {},
            "microsociology": {},
            "military_sociology": {},
            "natural_resource_sociology": {},
            "organizational_studies": {},
            "phenomenological_sociology": {},
            "policy_sociology": {},
            "polish_sociology": {},
            "postcolonialism": {},
            "psychoanalytic_sociology": {},
            "sexology": {},
            "social_capital": {},
            "social_change": {},
            "social_conflict_theory": {},
            "social_control": {},
            "social_economy": {},
            "social_philosophy": {},
            "social_psychology": {},
            "social_policy": {},
            "social_research": {},
            "sociology_of_aging": {},
            "sociology_of_agriculture": {},
            "sociology_of_art": {},
            "sociology_of_autism": {},
            "sociology_of_childhood": {},
            "sociology_of_conflict": {},
            "sociology_of_culture": {},
            "sociology_of_cyberspace": {},
            "sociology_of_deviance": {},
            "sociology_of_development": {},
            "sociology_of_disaster": {},
            "sociology_of_education": {},
            "sociology_of_emotions": {},
            "sociology_of_fatherhood": {},
            "sociology_of_film": {},
            "sociology_of_finance": {},
            "sociology_of_food": {},
            "sociology_of_gender": {},
            "sociology_of_generations": {},
            "sociology_of_globalization": {},
            "sociology_of_government": {},
            "sociology_of_health_and_illness": {},
            "sociology_of_human_consciousness": {},
            "sociology_of_immigration": {},
            "sociology_of_knowledge": {},
            "sociology_of_language": {},
            "sociology_of_law": {},
            "sociology_of_leisure": {},
            "sociology_of_literature": {},
            "sociology_of_markets": {},
            "sociology_of_marriage": {},
            "sociology_of_mothermood": {},
            "sociology_of_music": {},
            "sociology_of_natural_resources": {},
            "sociology_of_organizations": {},
            "sociology_of_peace_war_and_social_conflict": {},
            "sociology_of_punishment": {},
            "sociology_of_race_and_ethnic_relations": {},
            "sociology_of_religion": {},
            "sociology_of_risk": {},
            "sociology_of_science": {},
            "sociology_of_scientific_knowledge": {},
            "sociology_of_social_change": {},
            "sociology_of_social_movements": {},
            "sociology_of_space": {},
            "sociology_of_sport": {},
            "sociology_of_technology": {},
            "sociology_of_terrorism": {},
            "sociology_of_the_body": {},
            "sociology_of_the_family": {},
            "sociology_of_the_history_of_science": {},
            "sociology_of_the_internet": {},
            "sociology_of_work": {},
            "social_theory": {},
            "social_stratificiation": {},
            "sociological_theory": {},
            "sociobiology": {},
            "sociocybernetics": {},
            "sociolinguistics": {},
            "sociomusicology": {},
            "structural_sociology": {},
            "theoretical_sociology": {},
            "urban_sociology": {},
            "rural_sociology": {},
            "victimology": {},
            "visual_sociology": {}
        },
        "economics": {
            "agricultural_economics": {},
            "anarchist_economics": {},
            "applied_economics": {},
            "behavioural_economics": {},
            "bioeconomics": {},
            "business": {},
            "complexity_economics": {},
            "computational_economics": {},
            "consumer_economics": {},
            "development_economics": {},
            "digital_economics": {},
            "ecological_economics": {},
            "econometrics": {},
            "economic_geography": {},
            "economic_history": {},
            "economic_sector": {},
            "economic_sociology": {},
            "economic_systems": {},
            "economic_value": {},
            "energy_economics": {},
            "entrepreneurial_economics": {},
            "environmental_economics": {},
            "evolutionary_economics": {},
            "experimental_economics": {},
            "feminist_economics": {},
            "financial_economics": {},
            "green_economics": {},
            "growth_economics": {},
            "human_development_theory": {},
            "industrial_organization": {},
            "information_economics": {},
            "institutional_economics": {},
            "international_economics": {},
            "islamic_economics": {},
            "JEL_classification_codes": {},
            "knowledge_economy": {},
            "labor_economics": {},
            "law_and_economics": {},
            "macroeconomics": {},
            "managerial_economics": {},
            "market_economy": {},
            "marxian_economics": {},
            "mathematical_economics": {},
            "microeconomics": {},
            "monetary_economics": {},
            "neuroeconomics": {},
            "participatory_economics": {},
            "political_economy": {},
            "public_finance": {},
            "real_estate_economics": {},
            "resource_economics": {},
            "social_choice_theory": {},
            "socialist_economics": {},
            "socioeconomics": {},
            "transport_economics": {},
            "welfare_economics": {}
        },
        "political_science": {
            "american_politics": {},
            "canadian_politics": {},
            "civics": {},
            "comparative_politics": {},
            "european_studies": {},
            "geopolitics": {},
            "international_relations": {},
            "international organizations": {},
            "nationalism_studies": {},
            "peace_and_conflict_studies": {},
            "policy_studies": {},
            "political_behavior": {},
            "political_culture": {},
            "political_economy": {},
            "political_history": {},
            "political_philosophy": {},
            "psephology": {},
            "public_administration": {},
            "nonprofit_administration": {},
            "nongovernmental_organization_administration": {},
            "public_policy": {},
            "social_choice_theory": {}
        },
        "anthropology": {
            "cultural_anthropology": {},
            "biological_anthropology": {},
            "archaeological_anthropology": {},
            "linguistic_anthropology": {},
            "medical_anthropology": {},
            "forensic_anthropology": {}
        },
        "archaeology": {
            "aerial_archaeology": {},
            "aviation_archaeology": {},
            "anthracology": {},
            "archaeo-optics": {},
            "archaeoastronomy": {},
            "archaeogeography": {},
            "archaeological_culture": {},
            "archaeological_theory": {
                "great_ages_archaeology": {},
                "functionalism": {},
                "processualism": {},
                "post-processualism": {},
                "cognitive_archaeology": {},
                "gender_archaeology": {},
                "feminist_archaeology": {}
            },
            "archaeometry": {
                "archaeogenetics": {},
                "bioarchaeology": {},
                "computational_archaeology": {},
                "dendrochronology": {},
                "geoarchaeology": {},
                "isotope_analysis": {},
                "palynology": {},
                "radiocarbon_dating": {},
                "zooarchaeology": {}
            },
            "archaeology_of_religion_and_ritual": {},
            "archaeology_of_trade": {},
            "archaeomythology": {},
            "architectural_analytics": {},
            "battlefield_archaeology": {},
            "calceology": {},
            "conflict_archaeology": {},
            "data_archaeology": {},
            "digital_archaeology": {},
            "experimental_archaeology": {},
            "environmental_archaeology": {},
            "ethnoarchaeology": {},
            "forensic_archaeology": {},
            "glyptology": {},
            "history_of_archaeology": {},
            "household_archaeology": {},
            "landscape_archaeology": {},
            "manuscriptology": {},
            "maritime_archaeology": {},
            "media_archaeology": {},
            "modern_archaeology": {
                "settlement_archaeology": {}
            },
            "music_archaeology": {},
            "osteology": {},
            "palaeoarchaeology": {},
            "paleoanthropology": {},
            "paleopathology": {},
            "paleoradiology": {},
            "taphonomy": {},
            "urban_archaeology": {},
            "historical_archaeology": {
                "prehistoric_archaeology": {},
                "protohistoric_archaeology": {},
                "biblical_archaeology": {},
                "classical_archaeology": {},
                "egyptology": {},
                "assyriology": {},
                "etruscology": {},
                "near_eastern_archaeology": {},
                "medieval_archaeology": {},
                "post-medieval_archaeology": {},
                "industrial_archeaology": {},
                "contemporary_archaeology": {}
            }
        },
        "geography": {
            "cartography": {},
            "navigation": {},
            "human_geography": {
                "cultural_geography": {},
                "feminist_geography": {},
                "economic_geography": {},
                "development_geography": {},
                "historical_geography": {},
                "time_geography": {},
                "political_geography": {},
                "military_geography": {},
                "strategic_geography": {},
                "population_geography": {},
                "social_geography": {},
                "behaviorial_geography": {},
                "childrens_geographies": {},
                "health_geography": {},
                "tourism_geography": {},
                "urban_geography": {}
            },
            "environmental_geography": {},
            "physical_geography": {
                "biogeography": {},
                "climatology": {},
                "palaeoclimatology": {},
                "coastal_geography": {},
                "geomorphology": {},
                "geodesy": {},
                "hydrology_hydrography": {},
                "glaciology": {},
                "limnology": {},
                "biogeochemistry": {},
                "oceanography": {},
                "landscape_ecology": {},
                "palaeogeography": {},
            },
            "regional_geography": {},
            "remote_sensing": {}
        },
        "organizational_studies": {
            "business_economics": {},
            "business_ethics": {},
            "business_studies": {},
            "decision_science": {},
            "entrepreneurship": {},
            "human_resources_management": {},
            "industrial_organization": {},
            "management": {},
            "organizational_behavior": {},
            "organizational_thoery": {},
            "project_management": {},
            "quality_control": {},
            "strategy": {}
        },
    },
    "humanities": {
        "history": {
            "african_history": {
                "south_african_history": {},
                "egyptian_history": {},
                "nigerian_history": {},
            },
            "north_american_history": {
                "american_history": {},
                "canadian_history": {},
                "mexican_history": {},
                "cuban_history": {}
            },
            "south_american_history": {
                "latin_american_history": {},
                "brazilian_history": {},
                "colombian_history": {},
                "venezuelan_history": {},
                "peruvian_history": {},
                "argentine_history": {},
            },
            "pre_columbian_era": {
                "mayan_history": {},
                "aztec_history": {},
                "inca_history": {},
                "mississippian_culture": {},
                "native_american_history": {}
            },
            "ancient_history": {
                "ancient_greek_history": {},
                "ancient_roman_history": {
                    "history_roman_republic": {},
                    "history_roman_empire": {}
                },
                "ancient_egyptian_history": {},
                "ancient_chinese_history": {},
                "ancient_middle_eastern_history": {}
            },
            "asian_history": {
                "chinese_history": {},
                "japanese_history": {},
                "korean_history": {},
                "mongolian_history": {},
                "indian_history": {},
                "turkish_history": {},
                "iranian_history": {},
                "phillipine_history": {},
                "indonesian_history": {}
            },
            "european_history": {
                "british_history": {},
                "french_history": {},
                "german_history": {},
                "dutch_history": {},
                "italian_history": {},
                "spanish_history": {},
                "portuguese_history": {},
                "polish_history": {},
                "balkan_history": {},
                "scandinavian_history": {
                    "swedish_history": {},
                    "norwegian_history": {},
                    "danish_history": {},
                    "finnish_history": {},
                    "icelandic_history": {}
                },
                "russian_history": {}
            },
            "australian_history": {},
            "economic_history": {},
            "environmental_history": {},
            "intellectual_history": {},
            "modern_history": {},
            "political_history": {},
            "scientific_history": {},
            "technological_history": {},
            "world_history": {},
            "public_history": {}
        },
        "philosophy": {
            "meta_philosophy": {},
            "metaphysics": {
                "ontology": {},
                "teleology": {},
                "philosophy_of_mind": {},
                "philosophy_of_artificial_intelligence": {},
                "philosophy_of_perception": {},
                "philosophy_of_pain": {},
                "philosophy_of_space_and_time": {},
                "philosophy_of_action": {},
                "determinism_and_free_will": {}
            },
            "epistemology": {},
            "ethics": {
                "meta_ethics": {},
                "normative_ethics": {},
                "virtue_ethics": {},
                "applied_ethics": {},
                "ethics_of_animal_rights": {},
                "bio_ethics": {},
                "environmental_ethics": {},
                "moral_psychology": {},
                "descriptive_ethics": {},
                "value_theory": {}
            },
            "aesthetics": {},
            "philosophy_of_art": {},
            "social_philosophy": {},
            "political_philosophy": {},
            "platonism": {},
            "aristotelianism": {},
            "continental_philosophy": {},
            "eastern_philosophy": {},
            "feminist_philosophy": {},
            "history_of_philosophy": {},
            "ancient_philosophy": {},
            "medieval_philosophy": {},
            "logic": {
                "philosophical_logic": {},
                "mathematical_logic": {},
            },
            "philosophy_of_education": {},
            "philosophy_of_history": {},
            "philosophy_of_religion": {},
            "philosophy_of_language": {},
            "philosophy_of_law": {},
            "philosophy_of_mathematics": {},
            "philosophy_of_music": {},
            "philosophy_of_science": {},
            "philosophy_of_social_science": {},
            "philosophy_of_physics": {},
            "philosophy_of_biology": {},
            "philosophy_of_chemistry": {},
            "philosophy_of_economics": {},
            "philosophy_of_psychology": {},
            "philosophy_of_engineering": {},
            "systems_philosophy": {}
        },
        "languages": {
            "business_english": {},
            "classical_language": {},
            "modern_language": {},
            "standard_english": {},
            "world_englishes": {}
        },
        "linguistics": {
            "applied_linguistics": {},
            "comics_studies": {},
            "composition_studies": {},
            "discourse_analysis": {},
            "english_studies": {},
            "etymology": {},
            "grammar": {},
            "history_of_linguistics": {},
            "interlinguistics": {},
            "lexicology": {},
            "linguistic_topology": {},
            "natural_language_processing": {},
            "philosophy_of_language": {},
            "philosophy_of_linguistics": {},
            "linguistic_philosophy": {},
            "philology": {},
            "semantics": {},
            "semiotics": {},
            "terminology_science": {},
            "rhetoric": {},
            "word_usage": {},
            "phonetics": {},
            "phonology": {},
            "morphology": {},
            "syntax": {},
            "semantics": {},
            "pragmatics": {},
            "sociolinguistics": {},
            "psycholinguistics": {},
            "historical_linguistics": {},
            "computational_linguistics": {},
        },
        "literature": {
            "poetry": {},
            "comparative_literature": {},
            "english_literature": {},
            "world_literature": {},
            "american_literature": {},
            "british_literature": {},
            "history_of_literature": {},
            "medieval_literature": {},
            "post_colonial_literature": {},
            "post_modern_literature": {},
            "literary_theory": {},
            "critical_theory": {},
            "poetics": {},
            "rhetoric": {},
            "literary_genre": {},
            "creative_writing": {
                "creative_nonfiction": {},
                "fiction_writing": {},
                "non_fiction_writing": {},
                "literary_journalism": {},
                "screen_writing": {},
                "playwrighting": {},
            },
        },
        "divinity": {
            "canon_law": {},
            "church_history": {},
            "field_ministry": {
                "pastoral_counseling": {},
                "pastoral_theology": {},
                "religious_education": {},
                "homiletics": {},
                "liturgy": {},
                "sacred_music": {},
                "missiology": {}
            },
            "hermeneutics": {},
            "scriptural_study_and_languages": {
                "biblical_hebrew": {},
                "biblical_studies": {},
                "sacred_scripture": {},
                "vedic_study": {},
                "new_testament_greek": {},
                "latin": {},
                "old_church_slavonic": {}
            },
            "theology": {
                "dogmatic_theology": {},
                "ecclesiology": {},
                "sacramental_theology": {},
                "systemic_theology": {},
                "christian_ethics": {},
                "hindu_ethics": {},
                "moral_theology": {},
                "historical_theology": {}
            },
            "comparative_religion": {},
            "religious_history": {},
            "religious_philosophy": {},
            "biblical_studies": {},
            "islamic_studies": {},
            "buddhist_studies": {},
            "hindu_studies": {}
        },
        "performing_arts": {
            "music": {
                "accompanying": {},
                "chamber_music": {},
                "church_music": {},
                "musical_composition": {},
                "conducting": {
                    "choral_conducting": {},
                    "orchestral_conducting": {},
                    "wind_ensemble_conducting": {}
                },
                "early_music": {},
                "jazz_studies": {},
                "music_education": {},
                "music_history": {},
                "music_genre": {},
                "music_theory": {},
                "musicology": {
                    "historical_musicology": {},
                    "systematic_musicology": {},
                    "ethnomusicology": {}
                },
                "organology": {
                    "organ": {},
                    "piano": {},
                    "strings_harp_oud_guitar": {},
                    "singing": {},
                    "woodwinds": {},
                    "brass": {},
                    "percussion": {},
                },
                "recording": {},
                "orchestral_studies": {}                
            },
            "dance": {
                "choreography": {},
                "dance_notation": {},
                "ethnochoreology": {},
                "history_of_dance": {}
            },
            "television_studies": {},
            "theatre": {
                "history_of_theatre": {},
                "acting": {},
                "directing": {},
                "stage_design": {},
                "puppetry": {},
                "dramaturgy": {},
                "scenography": {},
                "musical_theatre": {}
            },
            "film": {
                "animation": {},
                "live_action": {},
                "film_making": {},
                "film_criticism": {},
                "film_genre": {},
                "film_studies": {},
                "film_theory": {}
            },
            "oral_literature": {
                "public_speaking": {},
                "performance_poetry": {},
                "spoken_word": {},
                "storytelling": {}
            },
            "electronic_game": {
                "arcade_games": {},
                "audio_games": {},
            }
        },
        "visual_arts": {
            "craft": {},
            "fine_arts": {},
            "forgery": {},
            "graphic_design": {},
            "painting": {},
            "sculpture": {},
            "architecture": {},
            "drawing": {},
            "printmaking": {},
            "photography": {},
            "ceramics": {},
            "art_history": {},
            "art_criticism": {},
            "digital_art": {}
        },
        "religious_studies": {
            "abrahamic_religions": {
                "christian_theology": {},
                "islamic_studies": {},
                "judaism_studies": {}
            },
            "apologetics": {},
            "indian_religions": {
                "buddhist_studies": {},
                "hinduism": {},
                "jainism": {},
                "sikhism": {}
            },
            "east_asian_religions": {
                "chinese_folk_religion": {},
                "confucianism": {},
                "shinto": {},
                "daoism": {},
                "i_kuan_tao": {},
                "caodaism": {},
                "chondogyo": {},
                "tenrikyo": {},
                "oomoto": {}
            },
            "african_religions": {},
            "ancient_egyptian_religion": {
                "kemitism": {},
            },
            "native_american_religions": {},
            "gnosticism": {},
            "occult": {},
            "esotericism": {},
            "mysticism": {},
            "spirituality": {},
            "sumerian_religion": {},
            "zoroastrianism": {},
            "comparative_religion": {},
            "mythology": {},
            "theism": {},
            "irreligion": {
                "agnosticism": {},
                "atheism": {},
                "religious_humanism": {},
                "nontheism": {}
            }            
        },
        "culinary_arts": {
            "acquired_taste": {},
            "aftertaste": {},
            "appetite": {},
            "artisanal_food": {},
            "cooking": {},
            "cuisine": {},
            "culinary_tourism": {},
            "delicacy": {},
            "diet": {},
            "flavor": {},
            "food_choice": {},
            "food_pairing": {},
            "food_photography": {},
            "food_preparation": {},
            "food_presentation": {},
            "food_safety": {},
            "food_security": {},
            "food_studies": {},
            "gastronomy": {},
            "gourmet": {},
            "palatability": {},
            "specialty_foods": {},
            "traditional_food": {}
        },
    },
    "professions_and_applied_sciences": {
        "agriculture": {
            "aeroponics": {},
            "agroecology": {},
            "agrology": {},
            "agronomy": {},
            "animal_husbandry": {},
            "beekeeping": {},
            "anthroponics": {},
            "agricultural_economics": {},
            "agricultural_engineering": {},
            "biological_systems_engineering": {},
            "food_engineering": {},
            "aquaculture": {},
            "aquaponics": {},
            "enology": {},
            "entomology": {},
            "fogponics": {},
            "food_science": {
                "culinary_arts": {}
            },
            "forestry": {},
            "horticulture": {},
            "hydrology": {},
            "pedology": {},
            "plant_science": {},
            "pomology": {},
            "pest_control": {},
            "purification": {},
            "vitculture": {}
        },
        "architecture_design": {
            "interior_architecture": {},
            "landscape_architecture": {},
            "architectural_analysis": {},
            "historic_preservation": {},
            "landscape_architecture": {},
            "landscape_design": {},
            "urban_planning": {},
            "visual_communication": {
                "graphic_design": {},
                "type_design": {},
                "technical_drawing": {}
            },
            "industrial_design": {
                "ergonomics": {},
                "toy_and_amusement_design": {}
            },
            "user_experience_design": {
                "interaction_design": {},
                "information_architecture": {},
                "user_interface_design": {},
                "user_experience_evaluation": {}
            },
            "decorative_arts": {},
            "fashion_design": {},
            "textile_design": {}
        },
        "business": {
            "accounting": {
                "accounting_research": {},
                "accounting_scholarship": {}
            },
            "business_administration": {},
            "business_analysis": {},
            "business_ethics": {},
            "business_law": {},
            "e_business": {},
            "entrepreneurship": {},
            "finance": {},
            "industrial_and_labor_relations": {
                "collective_bargaining": {},
                "human_resources": {},
                "organizational_studies": {},
                "labor_economics": {},
                "labor_history": {}
            },
            "information_systems": {
                "management_information_systems": {},
                "health_informatics": {}
            },
            "international_trade": {},
            "management": {},
            "marketing": {},
            "operations_management": {},
            "purchasing": {},
            "risk_management": {},
            "insurance": {},
            "systems_science": {}
        },
        "education": {
            "comparative_education": {},
            "critical_pedagogy": {},
            "cirriculum_and_instruction": {
                "alternative_education": {},
                "early_childhood_education": {},
                "elementary_education": {},
                "secondary_education": {},
                "higher_education": {},
                "mastery_learning": {},
                "cooperative_learning": {},
                "agricultural_education": {},
                "art_education": {},
                "bilingual_education": {},
                "chemistry_education": {},
                "counselor_education": {},
                "language_education": {},
                "legal_education": {},
                "mathematics_education": {},
                "medical_education": {},
                "military_education_and_training": {},
                "music_education": {},
                "nursing_education": {},
                "outdoor_education": {},
                "peace_education": {},
                "physical_education": {},
                "physics_education": {},
                "reading_education": {},
                "religious_education": {},
                "science_education": {},
                "sex_education": {},
                "sociology_of_education": {},
                "technology_education": {},
                "vocational_educations": {}
            },
            "educational_leadership": {},
            "educational_philosophy": {},
            "educational_psychology": {},
            "educational_technology": {},
            "distance_education": {}
        },
        "engineering": {
            "chemical_engineering": {
                "biocatalysts": {},
                "bioengineering": {
                    "biochemical_engineering": {},
                    "biomolecular_engineering": {},
                    "bionics": {}
                },
                "catalysis": {},
                "materials_engineering": {},
                "molecular_engineering": {},
                "nanotechnology": {},
                "polymer_engineering": {},
                "petroleum_engineering": {},
                "nuclear_engineering": {},
                "food_engineering": {},
                "process_engineering": {},
                "reaction_engineering": {},
                "thermodynamics": {},
                "transport_phenomena": {}
            },
            "civil_engineering": {
                "agricultural_engineering": {},
                "coastal_engineering": {},
                "construction": {},
                "earthquake_engineering": {},
                "ecological_engineering": {},
                "environmental_engineering": {},
                "geotechnical_engineering": {},
                "engineering_geology": {},
                "hydraulic_engineering": {},
                "infrastructure": {},
                "mining_engineering": {},
                "transportation_engineering": {},
                "highway_engineering": {},
                "structural_engineering": {},
                "architectural_engineering": {},
                "structural_mechanics": {},
                "surveying": {}
            },
            "electrical_engineering": {
                "applied_physics": {},
                "computer_engineering": {},
                "computer_science": {},
                "control_systems_engineering": {},
                "control_theory": {},
                "electronic_engineering": {
                    "electronics": {},
                    "instrumentation_engineering": {}
                },
                "engineering_physics": {},
                "photonics": {},
                "information_theory": {},
                "mechatronics": {},
                "power_engineering": {},
                "robotics": {
                    "microbotics": {}
                },
                "semiconductors": {},
                "telecommunications_engineering": {},
                "quantum_computing": {}
            },
            "materials_science_and_engineering": {
                "biomaterials": {},
                "ceramic_engineering": {},
                "corrosion_engineering": {},
                "crystallography": {},
                "nanomaterials": {},
                "photonics": {},
                "physical_metallurgy": {},
                "polymer_engineering": {},
                "polymer_science": {},
                "semiconductors": {}
            },
            "mechanical_engineering": {
                "aerospace_engineering": {
                    "aeronautics": {},
                    "astronautics": {}
                },
                "acoustical_engineering": {},
                "automotive_engineering": {},
                "biomedical_engineering": {},
                "biomechanical_engineering": {},
                "continuum_mechanics": {},
                "fluid_mechanics": {},
                "heat_transfer": {},
                "industrial_engineering": {},
                "manufacturing_engineering": {},
                "marine_engineering": {},
                "mass_transfer": {},
                "mechatronics": {},
                "nano_engineering": {},
                "ocean_engineering": {},
                "optical_engineering": {},
                "robotics": {},
                "thermal_engineering": {},
                "thermodynamics": {}
            },
        },
        "environmental_studies": {
            "environmental_management": {
                "coastal_management": {},
                "fisheries_management": {},
                "land_management": {},
                "natural_resource_management": {},
                "waste_management": {},
                "wildlife_management": {}
            },
            "environmental_policy": {},
            "wildlife_observation": {},
            "recreation_ecology": {},
            "silviculture": {},
            "sustainability_studies": {},
            "sustainable_development": {},
            "toxicology": {},
            "ecology": {},
        },
        "human_physical_performance_and_recreation": {
            "biomechanics": {},
            "sports_coaching": {},
            "escapology": {},
            "ergonomics": {},
            "physical_fitness": {
                "aerobics": {},
                "personal_fitness_training": {}
            },
            "game_design": {},
            "exercise_physiology": {},
            "kinesiology": {},
            "leisure_studies": {},
            "navigation": {},
            "outdoor_activity": {},
            "physical_activity": {},
            "physical_education": {},
            "sociology_of_sport": {},
            "sexology": {},
            "sports": {},
            "sports_journalism": {},
            "sport_management": {},
            "sport_psychology": {},
            "sports_medicine": {},
            "survival_skills": {
                "batoning": {},
                "bushcraft": {},
                "scoutcraft": {},
                "woodcraft": {},
            },
            "toy_and_amusement_design": {}
        },
        "journalism_media_studies_and_communication": {
            "journalism": {
                "broadcast_journalism": {},
                "digitial_journalism": {},
                "literary_journalism": {},
                "new_media_journalism": {},
                "print_journalism": {},
                "sports_journalism": {}
            },
            "media_studies": {
                "newspaper": {},
                "magazine": {},
                "radio": {},
                "television_studies": {},
                "film_studies": {},
                "game_studies": {},
                "fan_studies": {}
            },
            "narratology": {},
            "communication_studies": {
                "advertising": {},
                "animal_communication": {},
                "communication_design": {},
                "conspiracy_theory": {},
                "digital_media": {},
                "electronic_media": {},
                "environmental_communication": {},
                "hoaxes": {},
                "information_theory": {},
                "intercultural_communication": {},
                "marketing": {},
                "mass_communication": {},
                "nonverbal_communication": {},
                "organizational_communication": {},
                "popular_culture_studies": {},
                "propaganda_studies": {},
                "public_relations": {},
                "speech_communication": {},
                "technical_writing": {},
                "translation": {}
            }
        },
        "law": {
            "legal_management": {},
            "corporate_law": {},
            "mercantile_law": {},
            "business_law": {},
            "administrative_law": {},
            "canon_law": {},
            "comparative_law": {},
            "constitutional_law": {},
            "competition_law": {},
            "criminal_law": {
                "criminal_procedure": {},
                "criminal_justice": {
                    "police_science": {},
                    "forensic_science": {}
                }
            },
            "islamic_law": {},
            "jewish_law": {},
            "jurisprudence": {},
            "civil_law": {
                "admirality_law": {},
                "animal_law": {},
                "common_law": {},
                "corporations": {},
                "civil_procedure": {},
                "contract_law": {},
                "environmental_law": {},
                "family_law": {},
                "international_law": {
                    "public_international_law": {},
                    "supranational_law": {}
                },
                "labor_law": {},
                "paralegal_studies": {},
                "property_law": {},
                "tax_law": {},
                "tort_law": {},
            },
            "law_enforcement": {},
            "procedural_law": {},
            "substantive_law": {}
        },
        "library_and_museum_studies": {
            "archival_science": {},
            "bibliographic_databases": {},
            "bibliometrics": {},
            "cataloging": {
                "citation_analysis": {}
            },
            "categorization": {},
            "classification": {
                "library_classfication": {},
                "taxonomic_classification": {},
                "scientific_classification": {},
                "statistical_classification": {},
                "security_classification": {},
                "film_classification": {}
            },
            "collections_care": {},
            "collection_management": {},
            "conservation_science": {},
            "database_management": {},
            "data_modeling": {},
            "digital_preservation": {},
            "dissemination": {},
            "film_preservation": {},
            "historic_preservation": {},
            "history_of_library_science": {},
            "human_computer_interaction": {},
            "informatics": {},
            "information_architecture": {},
            "information_science": {},
            "knowledge_engineering": {},
            "knowledge_management": {},
            "museology": {},
            "museum_education": {},
            "records_management": {},

        },
        "medicine_and_health": {
            "alternative_medicine": {},
            "anesthesiology": {},
            "cleaning": {},
            "clinical_laboratory_science": {
                "clinical_biochemistry": {},
                "cytogenetics": {},
                "cytohematology": {},
                "cytology": {},
                "haemostasiology": {},
                "histology": {},
                "clinicial_immunology": {},
                "clinical_micobiology": {},
                "molecular_genetics": {},
                "parasitology": {}
            },
            "clinical_psychology": {},
            "cosmetology": {},
            "decontamination": {},
            "dentistry": {
                "dental_hygiene": {},
                "dental_surgery": {},
                "endodontics": {},
                "orthodontics": {},
                "oral_and_maxillofacial_surgery": {},
                "periodontics": {},
                "prosthodontics": {},
                "implantology": {},
            },
            "dermatology": {},
            "emergency_medicine": {},
            "health_informatics": {},
            "music_therapy": {},
            "nursing": {},
            "nutrition": {},
            "optometry": {},
            "orthoptics": {},
            "osteopaty": {},
            "physiotherapy": {},
            "occupational_theory": {},
            "speech_and_language_pathology": {},
            "preventative_medicine": {},
            "cardiology": {
                "cardiac_electrophysiology": {}
            },
            "dermatology": {},
            "pulmonology": {
                "medical_toxicology": {}
            },
            "endocrinology": {},
            "gastroenterology": {},
            "hepatology": {},
            "oncology": {},
            "geriatrics": {},
            "gynaecology": {},
            "hematology": {},
            "infectious_diseases": {},
            "nephrology": {},
            "neurology": {},
            "neurosurgery": {},
            "obstetrics": {},
            "ophthalmology": {
                "neuro_ophthalmology": {}
            },
            "orthopedic_surgery": {},
            "otolaryngology": {},
            "pathology": {},
            "pediatrics": {},
            "pharmacy": {},
            "pharmaceutical_sciences": {},
            "pharmacognosy": {},
            "physical_fitness": {
                "aerobics": {},
                "personal_fitness_training": {},
                "kinesiology": {}
            },
            "physical_therapy": {},
            "podiatry": {},
            "psychiatry": {},
            "psychology": {},
            "psychosomatic": {},
            "psychotherapy": {},
            "public_health": {},
            "radiology": {},
            "recreation_therapy": {},
            "rehabilitation_medicine": {},
            "respiratory_medicine": {
                "pulmonology": {},
                "sleep_medicine": {},
            },
            "respiratory_therapy": {},
            "rheumatology": {},
            "sports_medicine": {},
            "sterilization": {},
            "surgery": {
                "bariatric_surgery": {},
                "cardiothoracic_surgery": {},
                "neurosurgery": {},
                "plastic_surgery": {},
                "trauma_surgery": {},
                "traumatology": {}
            },
            "traditional_medicine": {},
            "therapy": {},
            "urology": {},
            "andrology": {},
            "veterinary_medicine": {}
        },
        "military_science": {
            "amphibious_warfare": {},
            "artillery": {},
            "battlespace": {},
            "campaigning": {},
            "military_engineering": {},
            "doctrine": {},
            "espionage": {},
            "game theory": {},
            "grand_strategy": {
                "containment": {},
                "limited_war": {},
                "philosophy_of_war": {},
                "strategic_studies": {},
                "total_war": {},
                "war": {}
            },
            "leadership": {},
            "logistics": {},
            "supply_chain_management": {},
            "military_operation": {},
            "military_history": {
                "prehistoric_military_history": {},
                "ancient_military_history": {},
                "early_modern_military_history": {},
                "industrial_military_history": {},
                "modern_military_history": {},
                "fourth_generation_warfare": {}
            },
            "military_intelligence": {},
            "military_law": {},
            "military_medicine": {},
            "naval_science": {
                "naval_engineering": {},
                "naval_tactics": {},
                "naval_architecture": {}
            },
            "military_organization": {
                "command_and_control": {},
                "military_doctrine": {},
                "military_education_and_training": {},
                "military_engineers": {},
                "military_ranks": {},
                "military_staff": {},
                "military_techonology_and_equipment": {},
                "military_exercises": {},
                "military_simulation": {},
                "military_sports": {}
            },
            "military_strategy": {
                "attrition_warfare": {},
                "military_deception": {},
                "strategic_defence": {},
                "military_offensive": {},
                "military_counter_offensive": {},
                "maneuver_warfare": {},
                "strategic_military_goal": {},
                "naval_strategy": {}
            },
            "military_tactics": {
                "air_combat_manoeuvring": {},
                "battle_tactics": {},
                "cavalry_tactics": {},
                "charge_maneuvers": {},
                "military_counter_offensive": {},
                "counterinsurgency": {},
                "counter_intelligence": {},
                "counter_terrorism": {},
                "defensive_fighting_positions": {},
                "endemic_warfare": {},
                "guerrilla_warfare": {},
                "infiltration": {},
                "irregular_warfare": {},
                "morale": {},
                "naval_tactics": {},
                "siege warfare": {},
                "surgical_strikes": {},
                "tactical_objectives": {},
                "trench_warfare": {}
            },
            "military_weapons": {
                "armor": {},
                "artillery": {},
                "biological_weapons": {},
                "cavalry": {},
                "conventional_weapons": {},
                "chemical_weapons": {},
                "cyber_weapons": {},
                "economic_warfare": {},
                "electronic_warfare": {},
                "infantry": {},
                "nuclear_weapons": {},
                "psychological_warfare": {},
                "unconventional_warfare": {}
            },
            "arms_control": {},
            "arms_race": {},
            "assassination": {},
            "asymmetric_warfare": {},
            "civil_defense": {},
            "cyberwarfare": {},
            "network-centric_warfare": {},
            "special_operations": {}
        },
        "public_administration": {
            "civil_service": {},
            "corrections": {},
            "conservation_biology": {},
            "criminal_justice": {},
            "disaster_research": {},
            "disaster_response": {},
            "emergency_management": {},
            "emergency_services": {},
            "fire_safety": {},
            "fire_ecology": {},
            "governmental_affairs": {},
            "international_affairs": {},
            "law_enforcement": {},
            "peace_and_conflict_studies": {},
            "police_science": {},
            "policy_studies": {
                "policy_analysis": {}
            },
            "nonprofit_administration": {},
            "non_governmental_organization_administration": {},
            "public_policy_doctrine": {},
            "public_policy_school": {},
            "regulation": {},
            "public_safety": {},
            "public_service": {},
            "public_policy": {
                "agricultural_policy": {},
                "commercial_policy": {},
                "cultural_policy": {},
                "domestic_policy": {},
                "drug_policy": {},
                "economic_policy": {
                    "fiscal_policy": {},
                    "incomes_policy": {},
                    "industrial_policy": {},
                    "investment_policy": {},
                    "monetary_policy": {},
                    "tax_policy": {}
                },
                "education_policy": {},
                "energy_policy": {
                    "nuclear_energy_policy": {},
                    "renewable_energy_policy": {}
                },
                "environmental_policy": {},
                "food_policy": {},
                "foreign_policy": {},
                "governance": {},
                "health_policy": {
                    "pharmaceutical_policy": {},
                    "vaccination_policy": {}
                },
                "housing_policy": {},
                "immigration_policy": {},
                "knowledge_policy": {},
                "language_policy": {},
                "military_policy": {},
                "science_policy": {
                    "climate_change_policy": {},
                    "stem_cell_research_policy": {},
                    "space_policy": {},
                    "technology_policy": {}
                },
                "security_policy": {},
                "social_policy": {},
            }
        }
    },
}

def get_all_subjects(taxonomy):
    """Generate a flattened list of all subjects."""
    subjects = []
    
    def flatten(structure, prefix=""):
        for key, value in structure.items():
            current = key if not prefix else f"{prefix}.{key}" 
            subjects.append(current)
            
            if value:  # If there are subcategories
                flatten(value, current)
    
    flatten(taxonomy)
    return sorted(subjects)

def save_taxonomy(taxonomy, output_dir="system_data", filename="subject_taxonomy.json"):
    """Save the taxonomy to a JSON file in the specified directory."""
    # Create the directory if it doesn't exist
    os.makedirs(output_dir, exist_ok=True)
    
    # Create the full path
    output_path = os.path.join(output_dir, filename)
    
    # Generate the all_subjects list
    all_subjects = get_all_subjects(taxonomy)
    
    # Create the complete taxonomy structure
    complete_taxonomy = {
        "hierarchy": taxonomy,
        "all_subjects": all_subjects
    }
    
    # Save to file
    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(complete_taxonomy, f, indent=2, ensure_ascii=False)
    
    print(f"Taxonomy saved to {output_path}")
    print(f"Generated {len(all_subjects)} subject categories")

def main():
    """Main function to generate and save the taxonomy."""
    save_taxonomy(BASE_TAXONOMY)

if __name__ == "__main__":
    main()



### Subjects to work Through
'''


'''